import { useState, useEffect } from "react";

// Map our topic names -> exact Wikipedia article titles for best image hit-rate
const WIKI_OVERRIDES = {
  // Dermatology
  "Psoriasis": "Psoriasis",
  "Lichen planus": "Lichen_planus",
  "Pemphigus vulgaris": "Pemphigus_vulgaris",
  "Bullous pemphigoid": "Bullous_pemphigoid",
  "Dermatitis herpetiformis": "Dermatitis_herpetiformis",
  "SJS / TEN": "Stevens%E2%80%93Johnson_syndrome",
  "Erythema multiforme": "Erythema_multiforme",
  "Erythema nodosum": "Erythema_nodosum",
  "Vitiligo": "Vitiligo",
  "Melasma": "Melasma",
  "Acanthosis nigricans": "Acanthosis_nigricans",
  "Leprosy patches": "Leprosy",
  "Molluscum contagiosum": "Molluscum_contagiosum",
  "Scabies": "Scabies",
  "Tinea corporis": "Tinea_corporis",
  "Pityriasis rosea": "Pityriasis_rosea",
  "Basal cell carcinoma": "Basal-cell_carcinoma",
  "Squamous cell carcinoma (skin)": "Squamous-cell_carcinoma_of_the_skin",
  "Melanoma": "Melanoma",
  "Café-au-lait spots": "Caf%C3%A9_au_lait_spot",
  "Impetigo": "Impetigo",
  "Eczema (atopic dermatitis)": "Atopic_dermatitis",

  // Ophthalmology
  "Mature cataract": "Cataract",
  "Acute angle-closure glaucoma": "Glaucoma",
  "Primary open angle glaucoma": "Glaucoma",
  "Diabetic retinopathy": "Diabetic_retinopathy",
  "Hypertensive retinopathy": "Hypertensive_retinopathy",
  "Papilledema": "Papilledema",
  "Optic atrophy": "Optic_neuropathy",
  "Retinal detachment": "Retinal_detachment",
  "Central retinal artery occlusion": "Central_retinal_artery_occlusion",
  "Central retinal vein occlusion": "Central_retinal_vein_occlusion",
  "Retinitis pigmentosa": "Retinitis_pigmentosa",
  "Age-related macular degeneration": "Macular_degeneration",
  "Hypopyon ulcer": "Hypopyon",
  "Pterygium": "Pterygium_(conjunctiva)",
  "Squint / Strabismus": "Strabismus",
  "Retinoblastoma": "Retinoblastoma",
  "Subconjunctival hemorrhage": "Subconjunctival_bleeding",
  "Stye (hordeolum)": "Stye",
  "Chalazion": "Chalazion",
  "Corneal arcus": "Arcus_senilis",
  "Trachoma": "Trachoma",
  "Keratoconus": "Keratoconus",

  // ENT
  "Acute suppurative otitis media": "Otitis_media",
  "Chronic suppurative otitis media": "Otitis_media",
  "Cholesteatoma": "Cholesteatoma",
  "Otosclerosis": "Otosclerosis",
  "Tympanic membrane perforation": "Perforated_eardrum",
  "Otitis externa": "Otitis_externa",
  "Nasal polyp": "Nasal_polyp",
  "DNS / Deviated nasal septum": "Nasal_septum_deviation",
  "Sinusitis": "Sinusitis",
  "Vocal cord polyp / Reinke edema": "Reinke%27s_edema",
  "Laryngeal carcinoma": "Laryngeal_cancer",
  "Quinsy (peritonsillar abscess)": "Peritonsillar_abscess",
  "Adenoid facies": "Adenoid_hypertrophy",
  "Epistaxis (Little's area)": "Nosebleed",

  // Chest X-rays
  "Pneumothorax": "Pneumothorax",
  "Tension pneumothorax": "Pneumothorax",
  "Pleural effusion": "Pleural_effusion",
  "Hydropneumothorax": "Hydropneumothorax",
  "Lobar pneumonia": "Lobar_pneumonia",
  "Tuberculosis (primary)": "Tuberculosis",
  "Tuberculosis (post-primary)": "Tuberculosis",
  "Miliary TB": "Miliary_tuberculosis",
  "Lung abscess": "Lung_abscess",
  "Bronchiectasis": "Bronchiectasis",
  "Pulmonary edema": "Pulmonary_edema",
  "ARDS": "Acute_respiratory_distress_syndrome",
  "Cardiomegaly": "Cardiomegaly",
  "Boot-shaped heart": "Tetralogy_of_Fallot",
  "Egg-on-side heart": "Transposition_of_the_great_vessels",
  "Snowman heart": "Total_anomalous_pulmonary_venous_connection",
  "Coin lesion": "Solitary_pulmonary_nodule",
  "Pancoast tumor": "Pancoast_tumor",
  "Mediastinal mass": "Mediastinal_tumor",
  "Silicosis": "Silicosis",
  "Asbestosis": "Asbestosis",
  "Sarcoidosis": "Sarcoidosis",
  "Pulmonary embolism (CXR)": "Pulmonary_embolism",
  "Rib notching": "Coarctation_of_the_aorta",
  "Aortic dissection": "Aortic_dissection",

  // Abdomen X-rays
  "Pneumoperitoneum": "Pneumoperitoneum",
  "Intestinal obstruction": "Bowel_obstruction",
  "Sigmoid volvulus": "Volvulus",
  "Cecal volvulus": "Volvulus",
  "Toxic megacolon": "Toxic_megacolon",
  "Thumbprinting sign": "Ischemic_colitis",
  "String sign (Crohn)": "Crohn%27s_disease",
  "Lead pipe colon": "Ulcerative_colitis",
  "Apple-core lesion": "Colorectal_cancer",
  "Double bubble sign": "Duodenal_atresia",
  "Triple bubble sign": "Jejunal_atresia",
  "Bird beak (esophagus)": "Achalasia",
  "Cork screw esophagus": "Esophageal_spasm",
  "Rat tail sign": "Esophageal_cancer",
  "Staghorn calculus": "Staghorn_calculus",
  "Gas under diaphragm": "Pneumoperitoneum",

  // CT/MRI
  "Extradural hematoma": "Epidural_hematoma",
  "Subdural hematoma": "Subdural_hematoma",
  "Subarachnoid hemorrhage": "Subarachnoid_hemorrhage",
  "Intracerebral hemorrhage": "Intracerebral_hemorrhage",
  "Ischemic stroke (acute)": "Stroke",
  "Brain tumor (Glioma)": "Glioma",
  "Meningioma": "Meningioma",
  "Hydrocephalus": "Hydrocephalus",
  "Multiple sclerosis": "Multiple_sclerosis",
  "Spinal cord compression / disc prolapse": "Spinal_disc_herniation",
  "Tuberculoma": "Tuberculoma",
  "Neurocysticercosis": "Cysticercosis",

  // Orthopedics
  "Colles fracture": "Colles%27_fracture",
  "Smith fracture": "Smith%27s_fracture",
  "Scaphoid fracture": "Scaphoid_fracture",
  "Monteggia fracture": "Monteggia_fracture",
  "Galeazzi fracture": "Galeazzi_fracture",
  "Bennett / Rolando fracture": "Bennett%27s_fracture",
  "Boxer fracture": "Boxer%27s_fracture",
  "Neck of femur fracture": "Hip_fracture",
  "Intertrochanteric fracture": "Hip_fracture",
  "Pott fracture": "Bimalleolar_fracture",
  "Greenstick fracture": "Greenstick_fracture",
  "Salter-Harris fractures": "Salter%E2%80%93Harris_fracture",
  "Osteosarcoma": "Osteosarcoma",
  "Ewing sarcoma": "Ewing%27s_sarcoma",
  "Giant cell tumor of bone": "Giant-cell_tumor_of_bone",
  "Multiple myeloma": "Multiple_myeloma",
  "Osteoarthritis": "Osteoarthritis",
  "Rheumatoid arthritis": "Rheumatoid_arthritis",
  "Gout (tophi)": "Gout",
  "Ankylosing spondylitis": "Ankylosing_spondylitis",
  "Pott's disease (spinal TB)": "Pott_disease",
  "Avascular necrosis of femoral head": "Avascular_necrosis",
  "Slipped capital femoral epiphysis": "Slipped_capital_femoral_epiphysis",
  "Perthes disease": "Legg%E2%80%93Calv%C3%A9%E2%80%93Perthes_disease",
  "Congenital DDH": "Hip_dysplasia",

  // Pathology
  "Granuloma": "Granuloma",
  "Reed-Sternberg cell": "Reed%E2%80%93Sternberg_cell",
  "Psammoma bodies": "Psammoma_body",
  "Mallory bodies": "Mallory_body",
  "Councilman bodies": "Councilman_body",
  "Negri bodies": "Negri_bodies",
  "Renal cell carcinoma": "Renal_cell_carcinoma",
  "Wilms tumor": "Wilms%27_tumor",
  "Pheochromocytoma": "Pheochromocytoma",
  "Hepatocellular carcinoma": "Hepatocellular_carcinoma",
  "Colorectal cancer": "Colorectal_cancer",
  "Krukenberg tumor": "Krukenberg_tumor",
  "Cervical CA": "Cervical_cancer",
  "Burkitt lymphoma": "Burkitt_lymphoma",
  "Pulmonary thromboembolus": "Pulmonary_embolism",
  "Atherosclerotic plaque": "Atherosclerosis",
  "Myocardial infarction (gross)": "Myocardial_infarction",
  "Caseation necrosis": "Caseous_necrosis",
  "Liquefactive necrosis": "Liquefactive_necrosis",
  "Coagulative necrosis": "Coagulative_necrosis",
  "Fat necrosis": "Fat_necrosis",
  "Fibrinoid necrosis": "Fibrinoid_necrosis",

  // Hematology smears
  "Sickle cells": "Sickle_cell_disease",
  "Target cells": "Target_cell",
  "Spherocytes": "Spherocytosis",
  "Schistocytes": "Schistocyte",
  "Howell-Jolly bodies": "Howell%E2%80%93Jolly_body",
  "Heinz bodies": "Heinz_body",
  "Bite cells (degmacytes)": "Degmacyte",
  "Pencil cells": "Iron-deficiency_anemia",
  "Tear-drop cells (dacrocytes)": "Dacrocyte",
  "Burr cells (echinocytes)": "Echinocyte",
  "Acanthocytes (spur cells)": "Acanthocyte",
  "Rouleaux formation": "Rouleaux",
  "Smudge cells": "Smudge_cell",
  "Auer rods": "Auer_rod",
  "Hypersegmented neutrophils": "Megaloblastic_anemia",
  "Atypical lymphocytes": "Infectious_mononucleosis",
  "Malaria parasites": "Plasmodium_falciparum",
  "Basophilic stippling": "Basophilic_stippling",

  // Microbiology
  "Gram +ve cocci in clusters": "Staphylococcus_aureus",
  "Gram +ve cocci in chains": "Streptococcus",
  "Gram -ve diplococci (intracellular)": "Neisseria_gonorrhoeae",
  "Acid-fast bacilli (ZN stain)": "Mycobacterium_tuberculosis",
  "India ink prep": "Cryptococcus_neoformans",
  "Owl's eye inclusion": "Cytomegalovirus",
  "Entamoeba histolytica": "Entamoeba_histolytica",
  "Hydatid cyst (Echinococcus)": "Echinococcosis",
  "Trichomonas vaginalis": "Trichomonas_vaginalis",
  "Candida albicans": "Candida_albicans",
  "Giardia lamblia": "Giardia_duodenalis",
  "Schistosoma haematobium": "Schistosoma_haematobium",
  "Ascaris lumbricoides": "Ascaris_lumbricoides",
  "Microfilaria": "Filariasis",

  // ECG & Cardiology
  "STEMI inferior wall": "Myocardial_infarction",
  "STEMI anterior wall": "Myocardial_infarction",
  "STEMI lateral wall": "Myocardial_infarction",
  "NSTEMI / Unstable angina": "Acute_coronary_syndrome",
  "Pericarditis": "Pericarditis",
  "Hyperkalemia": "Hyperkalemia",
  "Hypokalemia": "Hypokalemia",
  "Hypocalcemia": "Hypocalcaemia",
  "Hypercalcemia": "Hypercalcaemia",
  "WPW syndrome": "Wolff%E2%80%93Parkinson%E2%80%93White_syndrome",
  "Atrial fibrillation": "Atrial_fibrillation",
  "Atrial flutter": "Atrial_flutter",
  "Ventricular tachycardia": "Ventricular_tachycardia",
  "Torsades de pointes": "Torsades_de_pointes",
  "Ventricular fibrillation": "Ventricular_fibrillation",
  "First degree heart block": "First-degree_atrioventricular_block",
  "Mobitz type I (Wenckebach)": "Second-degree_atrioventricular_block",
  "Mobitz type II": "Second-degree_atrioventricular_block",
  "Complete heart block": "Third-degree_atrioventricular_block",
  "LBBB": "Left_bundle_branch_block",
  "RBBB": "Right_bundle_branch_block",
  "Left ventricular hypertrophy": "Left_ventricular_hypertrophy",
  "PE on ECG": "Pulmonary_embolism",
  "Cardiac tamponade": "Cardiac_tamponade",
  "Mitral stenosis (CXR)": "Mitral_stenosis",
  "Aortic stenosis (echo)": "Aortic_stenosis",

  // Pediatrics & Genetics
  "Down syndrome": "Down_syndrome",
  "Turner syndrome": "Turner_syndrome",
  "Klinefelter syndrome": "Klinefelter_syndrome",
  "Edwards syndrome (trisomy 18)": "Edwards_syndrome",
  "Patau syndrome (trisomy 13)": "Patau_syndrome",
  "Cleft lip and palate": "Cleft_lip_and_cleft_palate",
  "Hirschsprung disease": "Hirschsprung%27s_disease",
  "Pyloric stenosis": "Pyloric_stenosis",
  "Intussusception": "Intussusception_(medical_disorder)",
  "Kawasaki disease": "Kawasaki_disease",
  "Marfan syndrome": "Marfan_syndrome",
  "Neurofibromatosis type 1": "Neurofibromatosis_type_I",
  "Tuberous sclerosis": "Tuberous_sclerosis",
  "Sturge-Weber syndrome": "Sturge%E2%80%93Weber_syndrome",
  "Achondroplasia": "Achondroplasia",
  "Osteogenesis imperfecta": "Osteogenesis_imperfecta",
  "Rickets": "Rickets",

  // Endocrinology
  "Acromegaly": "Acromegaly",
  "Cushing syndrome": "Cushing%27s_syndrome",
  "Addison disease": "Addison%27s_disease",
  "Hypothyroidism": "Hypothyroidism",
  "Graves disease": "Graves%27_disease",
  "Goitre": "Goitre",
  "Multinodular goiter": "Toxic_multinodular_goitre",
  "Diabetic foot": "Diabetic_foot",
  "Necrobiosis lipoidica": "Necrobiosis_lipoidica",
  "Gynecomastia": "Gynecomastia",
  "Hirsutism (PCOS)": "Hirsutism",

  // OBGY
  "Hydatidiform mole": "Hydatidiform_mole",
  "Ectopic pregnancy": "Ectopic_pregnancy",
  "Placenta previa": "Placenta_praevia",
  "Placental abruption": "Placental_abruption",
  "Ovarian dermoid (teratoma)": "Mature_cystic_teratoma",
  "Ovarian cancer": "Ovarian_cancer",
  "Endometrial cancer": "Endometrial_cancer",
  "Uterine fibroid": "Uterine_fibroid",
  "Polycystic ovary syndrome": "Polycystic_ovary_syndrome",
  "Anencephaly": "Anencephaly",
  "Spina bifida": "Spina_bifida",
  "Cervical cancer": "Cervical_cancer",
  "Endometriosis": "Endometriosis",
  "Adenomyosis": "Adenomyosis",

  // Surgery — gross specimens
  "Gastric cancer": "Stomach_cancer",
  "Breast cancer": "Breast_cancer",
  "Fibroadenoma": "Fibroadenoma",
  "Phyllodes tumor": "Phyllodes_tumor",
  "Paget's disease of the nipple": "Paget%27s_disease_of_the_breast",
  "Papillary thyroid cancer": "Papillary_thyroid_cancer",
  "Inguinal hernia": "Inguinal_hernia",
  "Hydrocele": "Hydrocele_testis",
  "Varicocele": "Varicocele",
  "Testicular cancer": "Testicular_cancer",
  "Acute appendicitis": "Appendicitis",
  "Acute cholecystitis": "Cholecystitis",
  "Gallstones": "Gallstone",
  "Pancreatic pseudocyst": "Pancreatic_pseudocyst",
  "Cirrhosis": "Cirrhosis",
  "Liver abscess": "Liver_abscess",
  "Burn (Wallace rule of nines)": "Wallace_rule_of_nines",
  "Gangrene": "Gangrene",

  // Anesthesia & equipment
  "Laryngoscope": "Laryngoscopy",
  "Laryngeal mask airway": "Laryngeal_mask_airway",
  "Tracheal tube": "Tracheal_tube",
  "Magill forceps": "Magill_forceps",
  "Bag valve mask": "Bag_valve_mask",
  "Oropharyngeal airway": "Oropharyngeal_airway",
  "Mallampati score": "Mallampati_score",
  "ASA physical status classification system": "ASA_physical_status_classification_system",
  "Central venous catheter": "Central_venous_catheter",
  "Pulse oximetry": "Pulse_oximetry",
  "Capnography": "Capnography",
  "Anaesthetic vaporiser": "Anaesthetic_vaporiser",

  // Anatomy
  "Brachial plexus": "Brachial_plexus",
  "Circle of Willis": "Circle_of_Willis",
  "Cranial nerves": "Cranial_nerves",
  "Couinaud classification": "Couinaud_classification",
  "Bronchopulmonary segment": "Bronchopulmonary_segment",
  "Inguinal canal": "Inguinal_canal",
  "Femoral triangle": "Femoral_triangle",
  "Carpal bones": "Carpal_bones",
  "Tarsus (skeleton)": "Tarsus_(skeleton)",
  "Spinal cord": "Spinal_cord",
  "Heart development": "Heart_development",
  "Fetal circulation": "Fetal_circulation",

  // Forensic
  "Hanging": "Hanging",
  "Strangling": "Strangling",
  "Antemortem and postmortem injuries": "Wound",
  "Gunshot wound": "Gunshot_wound",
  "Stab wound": "Stab_wound",
  "Bruise": "Bruise",
  "Defensive wound": "Defensive_wound",
  "Livor mortis": "Livor_mortis",
  "Carbon monoxide poisoning": "Carbon_monoxide_poisoning",
  "Snakebite": "Snakebite",

  // ===== Added: derm expansion =====
  "SLE malar rash": "Systemic_lupus_erythematosus",
  "Discoid lupus": "Discoid_lupus_erythematosus",
  "Herpes zoster": "Shingles",
  "Chickenpox (varicella)": "Chickenpox",
  "Measles rash": "Measles",
  "Hand-foot-and-mouth disease": "Hand,_foot,_and_mouth_disease",
  "Syphilis (primary chancre)": "Syphilis",
  "Secondary syphilis": "Syphilis",
  "Urticaria": "Hives",
  "Alopecia areata": "Alopecia_areata",
  "Pellagra": "Pellagra",
  "Kwashiorkor": "Kwashiorkor",
  "Marasmus": "Marasmus",
  "Xanthelasma": "Xanthelasma",
  "Neurofibroma": "Neurofibroma",
  "Erysipelas": "Erysipelas",
  "Cellulitis": "Cellulitis",

  // ===== Added: ophth expansion =====
  "Roth spots": "Roth%27s_spot",
  "Kayser-Fleischer ring": "Kayser%E2%80%93Fleischer_ring",
  "Argyll Robertson pupil": "Argyll_Robertson_pupil",
  "Horner syndrome": "Horner%27s_syndrome",
  "Marcus Gunn (afferent pupillary defect)": "Relative_afferent_pupillary_defect",
  "Conjunctivitis": "Conjunctivitis",
  "Dacryocystitis": "Dacryocystitis",
  "Coloboma": "Coloboma",
  "Buphthalmos": "Buphthalmos",
  "Hyphema": "Hyphaema",
  "Cotton wool spots": "Cotton_wool_spots",
  "Foster Kennedy syndrome": "Foster_Kennedy_syndrome",

  // ===== Added: ENT expansion =====
  "Ludwig's angina": "Ludwig%27s_angina",
  "Thyroglossal cyst": "Thyroglossal_cyst",
  "Branchial cyst": "Branchial_cleft_cyst",
  "Cystic hygroma": "Cystic_hygroma",
  "Parotid tumor (pleomorphic adenoma)": "Pleomorphic_adenoma",
  "Tonsillitis": "Tonsillitis",
  "Diphtheria pseudomembrane": "Diphtheria",
  "Stomatitis (aphthous ulcer)": "Aphthous_stomatitis",
  "Oral leukoplakia": "Leukoplakia",
  "Oral submucous fibrosis": "Oral_submucous_fibrosis",
  "Foreign body ear (X-ray)": "Foreign_body",

  // ===== Added: chest expansion =====
  "Atelectasis": "Atelectasis",
  "Hampton's hump": "Hampton_hump",
  "Westermark sign": "Westermark_sign",
  "Hilar lymphadenopathy": "Mediastinal_lymphadenopathy",
  "Honeycomb lung": "Honeycomb_lung",
  "Lung cancer (mass)": "Lung_cancer",
  "Round atelectasis": "Round_atelectasis",
  "Empyema": "Empyema",
  "Diaphragmatic hernia": "Congenital_diaphragmatic_hernia",
  "Hyaline membrane disease (RDS)": "Infant_respiratory_distress_syndrome",
  "Meconium aspiration": "Meconium_aspiration_syndrome",
  "COPD on CXR": "Chronic_obstructive_pulmonary_disease",

  // ===== Added: abdomen expansion =====
  "Target sign (intussusception)": "Intussusception_(medical_disorder)",
  "Whirl sign (volvulus)": "Volvulus",
  "Ground-glass abdomen": "Meconium_ileus",
  "String of pearls sign": "Bowel_obstruction",
  "Coffee bean sign": "Volvulus",
  "Pneumobilia": "Pneumobilia",
  "Porcelain gallbladder": "Porcelain_gallbladder",
  "Riggler sign": "Pneumoperitoneum",
  "Lemon-on-stick (achalasia barium)": "Achalasia",
  "Hampton hump (abdomen — pseudo)": "Hampton_hump",
  "Renal cyst (Bosniak)": "Renal_cyst",

  // ===== Added: CT/MRI expansion =====
  "Brain abscess": "Brain_abscess",
  "Cerebellar tonsillar herniation (Chiari)": "Chiari_malformation",
  "Empty sella": "Empty_sella_syndrome",
  "Diffuse axonal injury": "Diffuse_axonal_injury",
  "Cerebral contusion": "Cerebral_contusion",
  "Aneurysm (berry)": "Intracranial_aneurysm",
  "AV malformation": "Arteriovenous_malformation",
  "Acoustic neuroma": "Vestibular_schwannoma",
  "Pituitary adenoma": "Pituitary_adenoma",
  "Craniopharyngioma": "Craniopharyngioma",
  "Lacunar infarcts": "Lacunar_stroke",
  "Multi-infarct dementia": "Vascular_dementia",
  "Spinal cord syrinx (syringomyelia)": "Syringomyelia",

  // ===== Added: ortho expansion =====
  "Supracondylar fracture humerus": "Supracondylar_humerus_fracture",
  "Clavicle fracture": "Clavicle_fracture",
  "Tibial plateau fracture": "Tibial_plateau_fracture",
  "Calcaneal fracture (Böhler angle)": "Calcaneal_fracture",
  "Talipes equinovarus (CTEV)": "Clubfoot",
  "Polydactyly": "Polydactyly",
  "Syndactyly": "Syndactyly",
  "Madelung deformity": "Madelung%27s_deformity",
  "Mandible fracture": "Mandibular_fracture",
  "Le Fort fractures": "Le_Fort_fracture_of_skull",
  "Compartment syndrome": "Compartment_syndrome",
  "Osteomyelitis": "Osteomyelitis",
  "Paget's disease of bone": "Paget%27s_disease_of_bone",
  "Osteopetrosis (marble bone)": "Osteopetrosis",
  "Osteoporosis": "Osteoporosis",
  "Osteoid osteoma": "Osteoid_osteoma",
  "Aneurysmal bone cyst": "Aneurysmal_bone_cyst",

  // ===== Added: pathology expansion =====
  "Fatty liver (steatosis)": "Fatty_liver_disease",
  "Crescentic glomerulonephritis": "Rapidly_progressive_glomerulonephritis",
  "IgA nephropathy": "IgA_nephropathy",
  "Membranous nephropathy": "Membranous_glomerulonephritis",
  "Minimal change disease": "Minimal_change_disease",
  "FSGS": "Focal_segmental_glomerulosclerosis",
  "Diabetic nephropathy": "Diabetic_nephropathy",
  "Acute tubular necrosis": "Acute_tubular_necrosis",
  "Pyelonephritis (gross)": "Pyelonephritis",
  "Glioblastoma multiforme": "Glioblastoma",
  "Astrocytoma": "Astrocytoma",
  "Medulloblastoma": "Medulloblastoma",
  "Ependymoma": "Ependymoma",
  "Adenocarcinoma lung": "Adenocarcinoma_of_the_lung",
  "Small cell lung CA": "Small-cell_carcinoma",
  "Squamous cell lung CA": "Squamous-cell_carcinoma_of_the_lung",
  "Mesothelioma": "Mesothelioma",
  "Thyroid follicular adenoma": "Thyroid_adenoma",
  "Medullary thyroid CA": "Medullary_thyroid_cancer",
  "Pancreatic adenocarcinoma": "Pancreatic_cancer",
  "Insulinoma": "Insulinoma",
  "Carcinoid tumor": "Carcinoid",
  "Bladder CA (transitional cell)": "Bladder_cancer",
  "Prostate adenocarcinoma": "Prostate_cancer",
  "BPH": "Benign_prostatic_hyperplasia",
  "Seminoma": "Seminoma",

  // ===== Added: heme expansion =====
  "Acute lymphoblastic leukemia": "Acute_lymphoblastic_leukemia",
  "Acute myeloid leukemia": "Acute_myeloid_leukemia",
  "Chronic myeloid leukemia": "Chronic_myelogenous_leukemia",
  "Chronic lymphocytic leukemia": "Chronic_lymphocytic_leukemia",
  "Multiple myeloma smear": "Multiple_myeloma",
  "Pelger-Huët anomaly": "Pelger%E2%80%93Hu%C3%ABt_anomaly",
  "Cabot rings": "Cabot_rings",
  "Pappenheimer bodies": "Pappenheimer_bodies",
  "Reticulocytes": "Reticulocyte",
  "Polycythemia vera": "Polycythemia_vera",
  "Essential thrombocytosis": "Essential_thrombocythemia",
  "Sezary cells": "S%C3%A9zary_disease",
  "Flower cells": "Adult_T-cell_leukemia/lymphoma",

  // ===== Added: micro expansion =====
  "Hookworm": "Hookworm_infection",
  "Enterobius vermicularis (pinworm)": "Pinworm_infection",
  "Taenia solium": "Taenia_solium",
  "Trypanosoma": "Trypanosoma",
  "Leishmania donovani": "Leishmania_donovani",
  "Toxoplasma gondii": "Toxoplasma_gondii",
  "Bacillus anthracis": "Bacillus_anthracis",
  "Clostridium tetani": "Clostridium_tetani",
  "Vibrio cholerae": "Vibrio_cholerae",
  "Treponema pallidum": "Treponema_pallidum",
  "Helicobacter pylori": "Helicobacter_pylori",
  "Aspergillus": "Aspergillosis",
  "Mucormycosis": "Mucormycosis",
  "Pneumocystis jirovecii": "Pneumocystis_jirovecii",
  "HSV multinucleated giant cells": "Herpes_simplex_virus",

  // ===== Added: ECG expansion =====
  "Right ventricular hypertrophy": "Right_ventricular_hypertrophy",
  "Right atrial enlargement (P pulmonale)": "Right_atrial_enlargement",
  "Left atrial enlargement (P mitrale)": "Left_atrial_enlargement",
  "Brugada syndrome": "Brugada_syndrome",
  "Long QT syndrome": "Long_QT_syndrome",
  "Digoxin effect": "Digoxin",
  "Hypothermia (Osborn / J wave)": "Osborn_wave",
  "Sinus bradycardia": "Sinus_bradycardia",
  "Sinus tachycardia": "Sinus_tachycardia",
  "Supraventricular tachycardia": "Supraventricular_tachycardia",
  "Premature ventricular contraction": "Premature_ventricular_contraction",
  "Atrial septal defect (RBBB pattern)": "Atrial_septal_defect",
  "Ventricular septal defect": "Ventricular_septal_defect",
  "Patent ductus arteriosus": "Patent_ductus_arteriosus",
  "Tetralogy of Fallot": "Tetralogy_of_Fallot",
  "Eisenmenger syndrome": "Eisenmenger_syndrome",
  "Cardiac myxoma": "Myxoma",
  "Infective endocarditis (vegetation)": "Infective_endocarditis",

  // ===== Added: pediatrics expansion =====
  "Scarlet fever": "Scarlet_fever",
  "Croup (steeple sign)": "Croup",
  "Epiglottitis (thumbprint sign)": "Epiglottitis",
  "Bronchiolitis (RSV)": "Bronchiolitis",
  "Henoch-Schönlein purpura": "IgA_vasculitis",
  "Erythema infectiosum (Fifth disease)": "Erythema_infectiosum",
  "Roseola infantum": "Roseola",
  "Mumps parotitis": "Mumps",
  "Hand-foot syndrome (sickle cell)": "Dactylitis",
  "Cretinism": "Congenital_hypothyroidism",
  "Russell-Silver dwarfism": "Silver%E2%80%93Russell_syndrome",
  "DiGeorge syndrome": "DiGeorge_syndrome",
  "Prader-Willi syndrome": "Prader%E2%80%93Willi_syndrome",
  "Angelman syndrome": "Angelman_syndrome",
  "Cri-du-chat syndrome": "Cri_du_chat_syndrome",
  "Fragile X syndrome": "Fragile_X_syndrome",
  "Williams syndrome": "Williams_syndrome",
  "Beckwith-Wiedemann syndrome": "Beckwith%E2%80%93Wiedemann_syndrome",

  // ===== Added: endo expansion =====
  "Gigantism": "Gigantism",
  "Pituitary dwarfism": "Growth_hormone_deficiency",
  "Pretibial myxedema": "Pretibial_myxedema",
  "Thyroid eye disease": "Graves%27_ophthalmopathy",
  "Hashimoto thyroiditis": "Hashimoto%27s_thyroiditis",
  "Carcinoid syndrome (flushing)": "Carcinoid_syndrome",
  "Diabetic dermopathy": "Diabetic_dermopathy",
  "Vitamin A deficiency (Bitot spots)": "Bitot%27s_spots",
  "Scurvy": "Scurvy",

  // ===== Added: OBGY expansion =====
  "Bishop score": "Bishop_score",
  "Partograph": "Partograph",
  "Cardiotocography": "Cardiotocography",
  "Twin pregnancy (USG)": "Twin",
  "Polyhydramnios": "Polyhydramnios",
  "Oligohydramnios": "Oligohydramnios",
  "Vesicular mole vs invasive": "Hydatidiform_mole",
  "Theca lutein cyst": "Theca_lutein_cyst",
  "Bartholin cyst": "Bartholin%27s_cyst",
  "Uterine prolapse": "Uterine_prolapse",
  "Vesicovaginal fistula": "Vesicovaginal_fistula",
  "Asherman syndrome": "Asherman%27s_syndrome",
  "Choriocarcinoma": "Choriocarcinoma",
  "Imperforate hymen": "Imperforate_hymen",
  "PCOS ovary": "Polycystic_ovary_syndrome",

  // ===== Added: surgery expansion =====
  "Fournier gangrene": "Fournier_gangrene",
  "Anal fistula": "Anal_fistula",
  "Pilonidal sinus": "Pilonidal_disease",
  "Diabetic ulcer": "Diabetic_foot_ulcer",
  "Venous ulcer": "Venous_ulcer",
  "Arterial ulcer": "Arterial_insufficiency_ulcer",
  "Marjolin ulcer": "Marjolin%27s_ulcer",
  "Keloid": "Keloid",
  "Lipoma": "Lipoma",
  "Sebaceous cyst": "Sebaceous_cyst",
  "Ganglion": "Ganglion_cyst",
  "Volvulus midgut": "Intestinal_malrotation",
  "Necrotizing enterocolitis": "Necrotizing_enterocolitis",
  "Meckel diverticulum": "Meckel%27s_diverticulum",
  "Intussusception (surgical)": "Intussusception_(medical_disorder)",
  "Achalasia (esophagogram)": "Achalasia",
  "Hiatus hernia": "Hiatal_hernia",
  "Stoma types": "Stoma_(medicine)",

  // ===== Added: anesthesia expansion =====
  "Spinal needle (Quincke)": "Spinal_needle",
  "Epidural catheter": "Epidural_administration",
  "Bain circuit (Mapleson D)": "Mapleson_circuit",
  "Soda lime canister": "Soda_lime",
  "Anesthesia machine": "Anaesthetic_machine",
  "Defibrillator": "Defibrillation",
  "Cricothyroidotomy": "Cricothyrotomy",
  "Boyle bottle (vaporizer)": "Anaesthetic_vaporiser",
  "Nasopharyngeal airway": "Nasopharyngeal_airway",

  // ===== Added: anatomy expansion =====
  "Pharyngeal arch": "Pharyngeal_arch",
  "Neural tube": "Neural_tube",
  "Skull (fontanelle)": "Fontanelle",
  "Diaphragm development": "Thoracic_diaphragm",
  "Knee joint": "Knee",
  "Shoulder joint anatomy": "Rotator_cuff",
  "Median nerve": "Median_nerve",
  "Ulnar nerve": "Ulnar_nerve",
  "Radial nerve": "Radial_nerve",
  "Sciatic nerve": "Sciatic_nerve",
  "Foot drop (peroneal nerve)": "Foot_drop",
  "Cubital fossa": "Cubital_fossa",
  "Popliteal fossa": "Popliteal_fossa",
  "Liver hilum (porta hepatis)": "Porta_hepatis",
  "Calot triangle": "Cystohepatic_triangle",
  "Aortic arch branches": "Aortic_arch",
  "Coronary arteries": "Coronary_circulation",
  "Triangle of pain (laparoscopic hernia)": "Inguinal_hernia_surgery",

  // ===== Added: forensic expansion =====
  "Rigor mortis": "Rigor_mortis",
  "Algor mortis": "Algor_mortis",
  "Drowning": "Drowning",
  "Electrocution (Joule burn)": "Electrical_injury",
  "Lightning (Lichtenberg figures)": "Lichtenberg_figure",
  "Petechiae (asphyxia)": "Asphyxia",
  "Burns ante vs post-mortem": "Burn",
  "Battered baby syndrome": "Child_abuse",
  "Sexual assault (hymenal injury)": "Sexual_assault",
  "Hesitation cuts": "Self-harm",
  "Coup-contrecoup injury": "Coup_contrecoup_injury",
  "Arsenic poisoning": "Arsenic_poisoning",
  "Mercury poisoning": "Mercury_poisoning",
  "Lead poisoning": "Lead_poisoning",
  "Opioid overdose": "Opioid_overdose",
  "Organophosphate poisoning": "Organophosphate_poisoning",
};

// In-memory cache so we don't re-fetch when reopening sections
const cache = new Map();

export default function WikiImage({ topic }) {
  const [src, setSrc] = useState(() => cache.get(topic)?.src || null);
  const [pageUrl, setPageUrl] = useState(() => cache.get(topic)?.pageUrl || null);
  const [status, setStatus] = useState(() => cache.has(topic) ? "done" : "loading");

  useEffect(() => {
    if (cache.has(topic)) return;
    let aborted = false;
    const title = WIKI_OVERRIDES[topic] || encodeURIComponent(topic);
    const url = `https://en.wikipedia.org/api/rest_v1/page/summary/${title}?redirect=true`;

    fetch(url)
      .then(r => r.ok ? r.json() : Promise.reject(r.status))
      .then(data => {
        if (aborted) return;
        const img = data.thumbnail?.source || data.originalimage?.source || null;
        const link = data.content_urls?.desktop?.page || null;
        cache.set(topic, { src: img, pageUrl: link });
        setSrc(img);
        setPageUrl(link);
        setStatus(img ? "done" : "noimg");
      })
      .catch(() => {
        if (aborted) return;
        cache.set(topic, { src: null, pageUrl: null });
        setStatus("error");
      });

    return () => { aborted = true; };
  }, [topic]);

  if (status === "loading") {
    return <div className="wiki-img wiki-img-skeleton" aria-label="Loading image…" />;
  }
  if (!src) {
    return (
      <div className="wiki-img wiki-img-empty">
        <span>No Wikipedia image — use search buttons below</span>
      </div>
    );
  }
  return (
    <a href={pageUrl || src} target="_blank" rel="noopener noreferrer" className="wiki-img-wrap" title="Open Wikipedia article">
      <img src={src} alt={topic} className="wiki-img" loading="lazy" />
      <div className="wiki-img-credit">📷 Wikipedia / Wikimedia Commons</div>
    </a>
  );
}
